import { useContext } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Slider from "rc-slider";
import "rc-slider/assets/index.css";
import Header from "../layout/header";
import Footer from "../layout/footer";
import ProductsBox from "../../../components/ProductsBox";
import StoreSlider from "../../../components/StoreSlider";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";
import "react-tabs/style/react-tabs.css";

const searchResult = {
  total: 786,
  countAreas: 7,
  distance: 2.32323,
};

const productList = [
  {
    id: "19029",
    icons: "nike-shoes-1.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19030",
    icons: "nike-shoes-2.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19031",
    icons: "nike-shoes-3.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19032",
    icons: "nike-shoes-4.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19033",
    icons: "nike-shoes-1.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19034",
    icons: "nike-shoes-2.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19035",
    icons: "nike-shoes-3.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19026",
    icons: "nike-shoes-4.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
];

const ConsumerStore: NextPage = () => {
  return (
    <div className="flex flex-col justify-center w-full">
      <Head>
         <title>IShopLocal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Header />
      <StoreSlider/>
      <div className="flex flex-col gap-4 px-[100px] justify-center items-center w-full pt-16">
        <p className=" font-bold text-[32px] text-iB pb-5 font-sfui">Products</p>
        <div className="flex flex-col w-full self-center py-6 mb-32 gap-5 col-span-9 ">
          <Tabs>
            <div className="flex justify-center">
              <TabList>
                <Tab>Dress Shoes</Tab>
                <Tab>Formal Shoes</Tab>
                <Tab>Sports Shoes</Tab>
              </TabList>
            </div>
            <TabPanel>
              <div className=" grid w-full gap-3 justify-between grid-cols-12 mt-14">
                {productList.map((item, index) => (
                  <ProductsBox
                    key={index}
                    id={item.id}
                    icons={item.icons}
                    brand={item.brand}
                    pricing={item.pricing}
                    rating={item.rating}
                    comment={item.comment}
                    likes={item.likes}
                    local={item.local}
                  />
                ))}
              </div>
            </TabPanel>
            <TabPanel>
              <div className=" grid w-full gap-3 justify-between grid-cols-12 mt-14">
                {productList.map((item, index) => (
                  <ProductsBox
                    key={index}
                    id={item.id}
                    icons={item.icons}
                    brand={item.brand}
                    pricing={item.pricing}
                    rating={item.rating}
                    comment={item.comment}
                    likes={item.likes}
                    local={item.local}
                  />
                ))}
              </div>
            </TabPanel>
            <TabPanel>
              <div className=" grid w-full gap-3 justify-between grid-cols-12 mt-14">
                {productList.map((item, index) => (
                  <ProductsBox
                    key={index}
                    id={item.id}
                    icons={item.icons}
                    brand={item.brand}
                    pricing={item.pricing}
                    rating={item.rating}
                    comment={item.comment}
                    likes={item.likes}
                    local={item.local}
                  />
                ))}
              </div>
            </TabPanel>
          </Tabs>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default ConsumerStore;
