import { useContext, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Header from "../layout/header";
import Footer from "../layout/footer";
import ProfileSideBar from "../../../components/ProfileSidbar";
import ProfileCPBox from "../../../components/ProfileCPBox";

const ItemList = [
  {
    cardNumber: "1030",
    icons: "visa.svg",
    type: "Visa",
    cardDate: "08/2025"
  },
  {
    cardNumber: "3001",
    icons: "master.svg",
    type: "Master",
    cardDate: "04/2034"
  }
];

const ProfilePayments: NextPage = () => {

  return (
    <div className="flex flex-col justify-center w-full">
      <Head>
        <title>IShopLocal | Profile/Payment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Header />
      <div className="grid grid-cols-12 gap-4 px-[100px] justify-center items-center w-full pt-16 font-sfui">
        <div className=" grid flex-col col-span-12 md:col-span-4 lg:col-span-3 gap-2 h-[100%] pt-8">
          <ProfileSideBar pageNumber={4}/>
        </div>
        <div className="grid w-full flex-col gap-8 col-span-12 md:col-span-8 lg:col-span-9 mb-32">
          <div className="w-full justify-between place-content-end flex ">
            <p className=" font-bold text-[32px] text-iB leading-none">
             Payment Method
            </p>
            <p className="flex font-medium text-[12px] text-iB items-end">
              Profile / Payment
            </p>
          </div>
          <div className="flex flex-col gap-4">
            <p className=" text-[20px] font-semibold font-sfui leading-none">
              Add Card
            </p>
            <div className="border-b border-cB w-full"></div>
            <div className="grid grid-cols-12 gap-5 pt-2">
              <div className=" flex gap-5 flex-col col-span-12 md:col-span-8 lg:col-span-8">
              <div className="grid grid-cols-12 gap-7">
                    <div className="grid flex-col col-span-12 gap-2">
                      <p className="text-dark text-[15px] font-medium">
                        Card Number
                      </p>
                      <div className="w-full rounded-lg border-[1px] border-cB p-3 bg-white">
                        <input
                          className="w-full text-[14px] font-medium leading-5 outline-0"
                          type="text"
                          style={{ color: "#000" }}
                          placeholder="0000 0000 0000 0000"
                        />
                      </div>
                    </div>
                  </div>
                  <div className="grid grid-cols-12 gap-7">
                    <div className="grid flex-col col-span-12 md:col-span-6 lg:col-span-6 gap-2">
                      <p className="text-dark text-[15px] font-medium">
                        Vallid Date
                      </p>
                      <div className="w-full rounded-lg border-[1px] border-cB p-3  bg-white">
                        <input
                          className="w-full text-[14px] font-medium leading-5 outline-0"
                          type="text"
                          style={{ color: "#000" }}
                          placeholder="Islamabad"
                        />
                      </div>
                    </div>
                    <div className="grid flex-col col-span-12 md:col-span-6 lg:col-span-6 gap-2">
                      <p className="text-dark text-[15px] font-medium">CVV</p>
                      <div className="w-full rounded-lg border-[1px] border-cB p-3  bg-white">
                        <input
                          className="w-full text-[14px] font-medium leading-5 outline-0"
                          type="text"
                          style={{ color: "#000" }}
                          placeholder="CVV"
                        />
                      </div>
                    </div>
                  </div>
                  <div className="w-full">
                    <p className="text-dark text-[15px] font-medium">
                      Your card details would be securely saved for fast
                      payments. Your CVV will not be Saved
                    </p>
                  </div>
                    <div className="flex justify-center py-[10px] mb-[10px] px-[20px] border-2 border-[hsl(191,100%,44%)] rounded-lg transition duration-0 cursor-pointer bg-[hsl(191,100%,44%)] hover:bg-[hsl(191,100%,44%)] hover:text-white hover:duration-150 gap-3 text-white w-[150px]">
                      <p className="font-sfui font-medium text-[14px]">
                        Add Card
                      </p>
                    </div>
              </div>
            </div>  
          </div>
          <div className="flex flex-col gap-4">
            <p className=" text-[20px] font-semibold font-sfui leading-none">
              Save Cards
            </p>
            <div className="border-b border-cB w-full"></div>
            <div className="flex gap-5 pt-2 flex-col">
              {ItemList.map((item, index) => (
              <ProfileCPBox
                key={index}
                cardNumber={item.cardNumber}
                icons={item.icons}
                type={item.type}
                cardDate={item.cardDate}
                />
              ))}
            </div>      
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default ProfilePayments;
