import { useContext, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import "rc-slider/assets/index.css";
import Header from "../layout/header";
import Footer from "../layout/footer";
import CartOrderBox from "../../../components/CartOrderBox";

const productList = [
  {
    id: "19029",
    icons: "nike-shoes-1.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19030",
    icons: "nike-shoes-2.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19031",
    icons: "nike-shoes-3.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19032",
    icons: "nike-shoes-4.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19033",
    icons: "nike-shoes-1.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19034",
    icons: "nike-shoes-2.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19035",
    icons: "nike-shoes-3.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19026",
    icons: "nike-shoes-4.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
];

const CartList = [
  {
    id: "19026",
    icons: "nike-shoes-1.png",
    pricing: "90.89",
    size: "43",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    flag: true,
  },
  {
    id: "19027",
    icons: "nike-shoes-4.png",
    pricing: "80.89",
    size: "46",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    flag: false,
  },
];

const CartOrderList = [
  {
    id: "19026",
    icons: "nike-shoes-1.png",
    pricing: "90.89",
    size: "43",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    numbers: 2,
  },
  {
    id: "19027",
    icons: "nike-shoes-4.png",
    pricing: "80.89",
    size: "46",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    numbers: 1,
  },
];

const ConsumerCart: NextPage = () => {
  const [payChange, setPayChange] = useState(false);
  const [address, setAddress] = useState("");
  return (
    <div className="flex flex-col justify-center w-full">
      <Head>
        <title>IShopLocal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Header />
      <div className="flex flex-col gap-4 px-[100px] justify-center items-center w-full pt-16 font-sfui">
        <div className="flex justify-between w-full flex-col gap-10">
          <p className=" font-bold text-[32px] text-iB font-sfui ">
            Shopping Cart
          </p>
          <div className="w-full grid grid-cols-12 gap-14 pb-32">
            {!payChange ? (
              <div className="flex flex-col col-span-12 md:col-span-7 lg:col-span-7 gap-5">
                <div className="flex flex-col gap-5 p-5 rounded-lg bg-[#F8F8F8]">
                  <p className=" text-[20px] font-semibold font-sfui">
                    Delivery Adress
                  </p>
                  <div className="border-b border-cB w-full"></div>
                  <div className="grid grid-cols-12 gap-7">
                    <div className="grid flex-col col-span-6 md:col-span-6 lg:col-span-6 gap-2">
                      <p className="text-dark text-[15px] font-medium">
                        First Name
                      </p>
                      <div className="w-full rounded-lg border-[1px] border-cB p-3 bg-white">
                        <input
                          className="w-full text-[14px] font-medium leading-5 outline-0"
                          type="text"
                          style={{ color: "#000" }}
                          placeholder="Jhon"
                        />
                      </div>
                    </div>
                    <div className="grid flex-col col-span-12 md:col-span-6 lg:col-span-6 gap-2">
                      <p className="text-dark text-[15px] font-medium">
                        Last Name
                      </p>
                      <div className="w-full rounded-lg border-[1px] border-cB p-3  bg-white">
                        <input
                          className="w-full text-[14px] font-medium leading-5 outline-0"
                          type="text"
                          style={{ color: "#000" }}
                          placeholder="Doe"
                        />
                      </div>
                    </div>
                  </div>
                  <div className="w-full flex flex-col gap-2">
                    <p className="text-dark text-[15px] font-medium">
                      Delivery Address
                    </p>
                    <div className="w-full rounded-lg border-[1px] border-cB p-3 bg-white">
                      <input
                        className="w-full text-[14px] font-medium leading-5 outline-0"
                        type="text"
                        style={{ color: "#000" }}
                        placeholder="Shop# 188, First Floor,Nike Centaurus Mall, Blue Area,F-8/G,"
                        value={address}
                        onChange={(e) => {
                          setAddress(e.target.value);
                        }}
                      />
                    </div>
                  </div>
                  <div className="grid grid-cols-12 gap-7">
                    <div className="grid flex-col col-span-12 md:col-span-6 lg:col-span-6 gap-2">
                      <p className="text-dark text-[15px] font-medium">City</p>
                      <div className="w-full rounded-lg border-[1px] border-cB p-3  bg-white">
                        <input
                          className="w-full text-[14px] font-medium leading-5 outline-0"
                          type="text"
                          style={{ color: "#000" }}
                          placeholder="Islamabad"
                        />
                      </div>
                    </div>
                    <div className="grid flex-col col-span-12 md:col-span-6 lg:col-span-6 gap-2 ">
                      <p className="text-dark text-[15px] font-medium">
                        Country
                      </p>
                      <div className="w-full rounded-lg border-[1px] border-cB p-3  bg-white">
                        <select name="" id="" className="outline-0 w-full">
                          <option value="0">Pakistan</option>
                          <option value="1">India</option>
                          <option value="2">Germany</option>
                        </select>
                      </div>
                    </div>
                  </div>
                  <Link href={"/consumer/cart/order"}>
                    <div className="flex justify-center py-[10px] px-[20px] border-2 border-cB rounded-lg transition duration-0 cursor-pointer hover:bg-[hsl(191,100%,44%)] hover:text-white hover:duration-150 gap-3 text-[#161828] w-[150px]">
                      <p className="font-sfui font-medium text-[14px]">
                        Save Changes
                      </p>
                    </div>
                  </Link>
                </div>
                <div
                  className="flex flex-col gap-5 p-5 rounded-lg bg-[#F8F8F8] cursor-pointer"
                  onClick={() => {
                    setPayChange(true);
                  }}>
                  <p className=" text-[20px] font-semibold font-sfui">
                    Payment Method
                  </p>
                  <div className="border-b border-cB w-full"></div>
                  <div className="flex w-full gap-10 ">
                    <Image
                      src="/icons/visa.svg"
                      alt="Visa"
                      className=""
                      width={66}
                      height={20}
                    />
                    <div className=" flex flex-col font-medium text-[14px]">
                      <p className=" ">**** **** **** 1234</p>
                      <p className="">Visa Card</p>
                    </div>
                    <div className=" flex flex-col gap-5 font-medium text-[14px]">
                      <p className=" ">08/2025</p>
                    </div>
                  </div>
                </div>
              </div>
            ) : (
              <div className="flex flex-col col-span-12 md:col-span-7 lg:col-span-7 gap-5">
                <div className="flex flex-col gap-5 p-5 rounded-lg bg-[#F8F8F8]">
                  <p className=" text-[20px] font-semibold font-sfui">
                    Delivery Adress
                  </p>
                  <div className="border-b border-cB w-full"></div>
                  <div className="grid grid-cols-12 justify-between gap-5">
                    <p
                      className=" text-[16px] font-medium col-span-12 md:col-span-7 lg:col-span-7 w-full"
                      style={{ overflowWrap: "anywhere" }}>
                      {address}
                    </p>
                    <div className="col-span-12 md:col-span-5 lg:col-span-5 flex justify-end">
                      <div
                        className="flex justify-center py-[10px] px-[30px] border-2 border-cB rounded-lg transition duration-0 cursor-pointer hover:bg-[hsl(191,100%,44%)] hover:text-white hover:duration-150 gap-3 text-[#161828] w-[120px]"
                        onClick={() => {
                          setPayChange(false);
                        }}>
                        <p className="font-sfui font-medium text-[16px] ">
                          Change
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="flex flex-col gap-5 p-5 rounded-lg bg-[#F8F8F8] cursor-pointer">
                  <p className=" text-[20px] font-semibold font-sfui">
                    Payment Method
                  </p>
                  <div className="border-b border-cB w-full"></div>
                  <div className="grid grid-cols-12 gap-7">
                    <div className="grid flex-col col-span-12 gap-2">
                      <p className="text-dark text-[15px] font-medium">
                        Card Number
                      </p>
                      <div className="w-full rounded-lg border-[1px] border-cB p-3 bg-white">
                        <input
                          className="w-full text-[14px] font-medium leading-5 outline-0"
                          type="text"
                          style={{ color: "#000" }}
                          placeholder="0000 0000 0000 0000"
                        />
                      </div>
                    </div>
                  </div>
                  <div className="grid grid-cols-12 gap-7">
                    <div className="grid flex-col col-span-12 md:col-span-6 lg:col-span-6 gap-2">
                      <p className="text-dark text-[15px] font-medium">
                        Vallid Date
                      </p>
                      <div className="w-full rounded-lg border-[1px] border-cB p-3  bg-white">
                        <input
                          className="w-full text-[14px] font-medium leading-5 outline-0"
                          type="text"
                          style={{ color: "#000" }}
                          placeholder="Islamabad"
                        />
                      </div>
                    </div>
                    <div className="grid flex-col col-span-12 md:col-span-6 lg:col-span-6 gap-2">
                      <p className="text-dark text-[15px] font-medium">CVV</p>
                      <div className="w-full rounded-lg border-[1px] border-cB p-3  bg-white">
                        <input
                          className="w-full text-[14px] font-medium leading-5 outline-0"
                          type="text"
                          style={{ color: "#000" }}
                          placeholder="CVV"
                        />
                      </div>
                    </div>
                  </div>
                  <div className="w-full">
                    <p className="text-dark text-[15px] font-medium">
                      Your card details would be securely saved for fast
                      payments. Your CVV will not be Saved
                    </p>
                  </div>
                    <div className="flex justify-center py-[10px] mb-[10px] px-[20px] border-2 border-cB rounded-lg transition duration-0 cursor-pointer hover:bg-[hsl(191,100%,44%)] hover:text-white hover:duration-150 gap-3 text-[#161828] w-[150px]">
                      <p className="font-sfui font-medium text-[14px]">
                        Add Card
                      </p>
                    </div>
                </div>
              </div>
            )}

            <div className="flex flex-col col-span-12 md:col-span-5 lg:col-span-5 gap-5 p-5">
              <div className="flex flex-col gap-4">
                {CartOrderList.map((item, index) => (
                  <CartOrderBox
                    key={index}
                    id={item.id}
                    icons={item.icons}
                    pricing={item.pricing}
                    size={item.size}
                    comment={item.comment}
                    numbers={item.numbers}
                  />
                ))}
              </div>
              <div className="px-5 flex flex-col gap-5">
                <div className="flex flex-col gap-3 w-full px-5 py-5 bg-[#F8F8F8] font-sfui rounded-lg">
                  <div className="w-full flex justify-between text-[14px]">
                    <p className="text-[#696C74]">SubTotal</p>
                    <p className="font-medium">$1000</p>
                  </div>
                  <div className="w-full flex justify-between text-[14px]">
                    <p className="text-[#696C74]">Delivery Fee</p>
                    <p className="font-medium">$30</p>
                  </div>
                  <div className="w-full flex justify-between text-[14px]">
                    <p className="text-[#696C74]">Tax</p>
                    <p className="font-medium">57</p>
                  </div>
                  <div className="border-b border-cB w-full"></div>
                  <div className="w-full flex justify-between text-[14px]">
                    <p className=" font-medium">Total</p>
                    <p className="text-[#00B5DE] font-medium text-[16px]">{`USD ${"1560.00"}`}</p>
                  </div>
                </div>
                <div className="flex justify-center py-[10px] px-[20px] border-2 border-cB rounded-lg transition duration-0 cursor-pointer hover:bg-[hsl(191,100%,44%)] hover:text-white hover:duration-150 gap-3 text-[#161828]">
                  <p className="font-sfui font-medium text-[18px]">
                    {`Confirm Order $${"1560.00"}`}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default ConsumerCart;
