import { useContext } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Slider from "rc-slider";
import "rc-slider/assets/index.css";
import Header from "../layout/header";
import Footer from "../layout/footer";
import ProductsBox from "../../../components/ProductsBox";
import { FiFilter } from "react-icons/fi";
import { AiOutlineShoppingCart } from "react-icons/ai";

const searchResult = {
  total: 786,
  countAreas: 7,
  distance: 2.32323,
};

const productList = [
  {
    id: "19029",
    icons: "nike-shoes-1.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19030",
    icons: "nike-shoes-2.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19031",
    icons: "nike-shoes-3.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19032",
    icons: "nike-shoes-4.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19033",
    icons: "nike-shoes-1.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19034",
    icons: "nike-shoes-2.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19035",
    icons: "nike-shoes-3.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
  {
    id: "19026",
    icons: "nike-shoes-4.png",
    brand: "Nike",
    pricing: "90.89",
    rating: "4.8",
    comment: "Dr. Martens 1460 Women's Black Nappa 8 Eye Boot",
    likes: "56,743",
    local: "Antwerp Area",
  },
];

const ConsumerWishList: NextPage = () => {
  return (
    <div className="flex flex-col justify-center w-full">
      <Head>
        <title>IShopLocal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Header />
      <div className="flex flex-col gap-4 px-[100px] justify-center items-center w-full pt-16">
        <div className="flex justify-between w-full items-center">
          <p className=" font-bold text-[32px] text-iB font-sfui self-center ">
            WhishList
          </p>
          <div className="flex gap-5">
            {/* <Link href={"/consumer/products"}> */}
            <div className="flex justify-center items-center py-[10px] px-[20px] border-2 border-cB rounded-lg transition duration-0 cursor-pointer hover:bg-[hsl(191,100%,44%)] hover:text-white hover:duration-150 gap-3 text-[#161828] px-">
              <FiFilter fontSize={20} />
              <p className="font-sfui font-medium text-[14px]">
                Filter
              </p>
            </div>
            {/* </Link> */}
            {/* <Link href={"/consumer/products"}> */}
            <div className="flex justify-center items-center py-[1px] px-[20px] border-2 border-cB rounded-lg transition duration-0 cursor-pointer hover:bg-[hsl(191,100%,44%)] hover:text-white hover:duration-150 gap-3 text-[#161828]">
              <AiOutlineShoppingCart fontSize={20} />
              <p className="font-sfui font-medium text-[14px]">
                Move all to cart
              </p>
            </div>
            {/* </Link> */}
          </div>
        </div>
        <div className="flex flex-col w-full self-center py-6 mb-32 gap-5 col-span-9 ">
          <div className=" grid w-full gap-3 justify-between grid-cols-12 mt-14">
            {productList.map((item, index) => (
              <ProductsBox
                key={index}
                id={item.id}
                icons={item.icons}
                brand={item.brand}
                pricing={item.pricing}
                rating={item.rating}
                comment={item.comment}
                likes={item.likes}
                local={item.local}
              />
            ))}
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default ConsumerWishList;
