import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>IShopLocal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <div className="bg-cover bg-center bg-[url('/img/bg-login.png')] w-full flex justify-center items-center min-h-screen	">
        <div className="sm:w-[100%] md:w-[80%] lg:w-[40%] bg-white p-12 flex flex-col gap-5 font-sfui">
          <div className="flex flex-col">
            <p className="text-dark text-[25px] tracking-none font-semibold leading-10 ">
              Welcome back Rerailer
            </p>
            <p className="text-[#A0A3A7] text-[15px] leading-10">
              {" "}
              Welcome back! Please enter your Details{" "}
            </p>
          </div>
          <div className="flex flex-col gap-2">
            <p className="text-dark text-[15px] font-medium">Email</p>
            <div className="w-full rounded-lg border-[1px] border-cB p-3 ">
              <input
                className="font-manrope w-full text-[14px] font-medium leading-5 outline-0"
                type="email"
                style={{ color: "#000" }}
                placeholder="Retailer@shop.com"
              />
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <p className="text-dark text-[15px] font-medium">Password</p>
            <div className="w-full rounded-lg border-[1px] border-cB p-3 ">
              <input
                className="font-manrope w-full text-[14px] font-medium leading-5 outline-0"
                type="password"
                style={{ color: "#000" }}
                placeholder="************"
              />
            </div>
          </div>
          <p className="text-dark text-[15px] font-medium self-end">
            Forgot Password
          </p>
          <Link href={"/consumer"}>
            <div className="flex justify-center items-center w-full p-[10px] rounded-lg bg-[#111727] transition duration-0 cursor-pointer hover:opacity-80 hover:duration-150 ">
              <p className="text-white font-medium text-[14px]">Sign in</p>
            </div>
          </Link>
          <div className="flex w-full justify-between items-center">
            <div className="border-b-2 border-cB w-[45%]"></div>
            <p>or</p>
            <div className="border-b-2 border-cB w-[45%]"></div>
          </div>
          <div className="flex justify-center items-center w-full p-[10px] rounded-lg bg-white border-[1px] border-cB gap-6 transition duration-0 cursor-pointer hover:bg-cB hover:duration-150 ">
            <Image
              src="/icons/google.svg"
              alt="Google"
              width={20}
              height={20}
            />
            <p className="text-dark font-medium text-[14px]">
              Sign in with Google
            </p>
          </div>
          <div className="flex justify-center items-center w-full p-[10px] rounded-lg bg-white border-[1px] border-cB gap-6 transition duration-0 cursor-pointer hover:bg-cB hover:duration-150 ">
            <Image src="/icons/apple.svg" alt="Apple" width={20} height={20} />
            <p className="text-dark font-medium text-[14px]">
              Sign in with Apple
            </p>
          </div>
          <p className="text-[14px] text-dark">
            Don’t have an account?{" "}
            <a className=" font-semibold font-sfui">Sign up for free</a>
          </p>
        </div>
      </div>
    </div>
  );
};

export default Home;
